aws.region=${AWS_REGION:eu-central-1}
aws.s3.bucket=${STATIC_BUCKET_NAME:photo-gallery-dir-266735814394-eu-central-1}
aws.cloudfront.domain=${CLOUDFRONT_DOMAIN:ddtjsubulqq63x.cloudfront.net}

db.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:photogallery}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}